### PR TITLE
fontawesome icon support

### PR DESCRIPTION
**Pull request by Adnatull**
Font Awesome version 5.4.1. User can use all the relevant icons as fontawesome icon use instruction.

### CODE REVIEW

**Comment by sanonz** [comment]
Thank you so much for your contribution. Could you make a usage samples for this?

**Comment by Adnatull** [comment]
First need to choose an icon from `https://fontawesome.com`. I want to change default icomoon github icon in `"\layout\_partial\aside.ejs"` line number 32.   I will replace the icon by "https://fontawesome.com/icons/github-square?style=brands" .  From the link i copied `<i class="fab fa-github-square"></i>` and replaced `<i class="icon-github">` . 
So the 32 N.O. line become like this                     `<a class="thread-item" href="https://github.com/adnatull" target="_blank"><i class="fab fa-github-square"></i></a>`
Now you can see the effect in your browser.

**Comment by sanonz** [comment]
I think it's a little big, it's just used in `aside.ejs`, `aside.ejs` only include a few icon. I got an idea from you, create a directory for your icons, configure svg path and url fields:
```yml
links:
  - svg: ./source/svg/github.svg
    url: https://github.com/sanonz
  - svg: ./source/svg/more.svg
    url: http://weibo.com/sanonz
  - svg: ./source/svg/twitter.svg
    url: https://twitter.com/sanonze
```
This ensures that only the needed icons are built, But the steps are a bit more cumbersome, You need to download the icons and put it in `./source/svg` directory, Do you think?

**Comment by sanonz** [comment]
Try this 587d84f598ea98e6d0ed9fd260cfaa5c1e0605f3

**Comment by Adnatull** [comment]
I was not aware about keeping the size in minimal. In this case having options of choosing large numbers of webfonts are not actually required! Your current approach is more understanding though user have to download the svg beforehand. I am new in hexo world. Your theme helped me a lot.

**Pull request closed without merging**
